### ISSUE TITLE
Support new iPhones screen ratio

### ISSUE THREAD

**Issue by marcoscurvello** [abury/ABPadLockScreen#37] opened 2014-12-16 14:57 UTC
Is there a plan to support for the new iPhones screen size?

**Comment by abury** [comment] 2015-07-09 01:01
Hey @marcoscurvello 
What are the current issues? I've tested this on the iPhone 4, 5s, 6 & 6+ and it all seems to be working fine.
What issues are you experiencing?

**Comment by syky27** [comment] 2015-08-14 03:42
I have probably found the bug @marcoscurvello is talking about. In case you have setted up a background view, on a new iPhones (iPhone 6 & iPhone 6 Plus) blurring view is applied, but not for the whole screen that is caused by this:
```
_contentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, MIN(frame.size.height, 568.0f))];
```
IMHO if you will decide to make contentView bigger it doesn't look as good as if it stays smaller.
So what I did is that I changed this
```
_backgroundBlurringView.frame = _contentView.frame;

```
to this:
```
_backgroundBlurringView.frame = self.frame;
```

This changes are made in `ABPadLockScreenSetupView.m`

See my Pull Request...

<img width="423" alt="iPhone 6 Plus blurring bug" src="https://cloud.githubusercontent.com/assets/2771802/9266870/b8834ff0-41fb-11e5-9127-272b83b25289.png">

**Comment by abury** [comment] 2015-08-15 01:59
Ah I see. That makes sense. Thanks for bringing it up!
I'll try and have a look at this in the next few days.

**Comment by syky27** [comment] 2015-08-15 04:40
My pleasure.

**Comment by syky27** [comment] 2015-08-27 15:19
Well tested and it works.

**Comment by abury** [comment] 2015-09-13 06:15
This has been merged closed.

**Closed by abury** 2015-09-13 06:15 UTC
